apiVersion: v1
kind: Pod
metadata:
  name: count
spec:
  containers:

  - name: html-generator
    image: gasbugs/count
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    volumeMounts:
    - name: html
      mountPath: /var/htdocs

  - name: web-server
    image: httpd
    volumeMounts:
    - name: html
      mountPath: /usr/local/apache2/htdocs
      readOnly: true
    ports:
    - containerPort : 80
      protocol: TCP

  volumes:
  - name: html
    emptyDir: {}

