apiVersion: v1
kind: Pod
metadata:
  name: count
spec:
  containers:

  - name: html-generator
    image: seokhyeon116/count
    #image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
